// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7zksZKmklQ7EXcjaK5_926Z1xSvtK7ew',
    appId: '1:390666625123:web:621ee12bd5dea17e11d856',
    messagingSenderId: '390666625123',
    projectId: 'lab10-flutter-d8e55',
    authDomain: 'lab10-flutter-d8e55.firebaseapp.com',
    storageBucket: 'lab10-flutter-d8e55.firebasestorage.app',
    measurementId: 'G-Z7L2DKZ7N2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcdoio3QD-qr6hY4Uh1B_eRB9XjJ3SSHc',
    appId: '1:390666625123:android:4cc33745b03e873811d856',
    messagingSenderId: '390666625123',
    projectId: 'lab10-flutter-d8e55',
    storageBucket: 'lab10-flutter-d8e55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCixKUemA57GRPdf1ZHcOwnVN2DZlj3U0U',
    appId: '1:390666625123:ios:6bf741fe9ddf4c3611d856',
    messagingSenderId: '390666625123',
    projectId: 'lab10-flutter-d8e55',
    storageBucket: 'lab10-flutter-d8e55.firebasestorage.app',
    iosBundleId: 'com.example.lab10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCixKUemA57GRPdf1ZHcOwnVN2DZlj3U0U',
    appId: '1:390666625123:ios:6bf741fe9ddf4c3611d856',
    messagingSenderId: '390666625123',
    projectId: 'lab10-flutter-d8e55',
    storageBucket: 'lab10-flutter-d8e55.firebasestorage.app',
    iosBundleId: 'com.example.lab10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7zksZKmklQ7EXcjaK5_926Z1xSvtK7ew',
    appId: '1:390666625123:web:91d557e5552c25b411d856',
    messagingSenderId: '390666625123',
    projectId: 'lab10-flutter-d8e55',
    authDomain: 'lab10-flutter-d8e55.firebaseapp.com',
    storageBucket: 'lab10-flutter-d8e55.firebasestorage.app',
    measurementId: 'G-J3BPJK0H09',
  );
}
